<?php
/** @var $this App\TemplateEngine */
/** @var $content string */
/** @var \App\Models\UsersRow $user */

$hbPriority = 10;
$this->headBlock()
    ->addBlock('    <link href="'.$this->sitePrefixPath().'/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />' . "\n", "bootstrap.min.css", $hbPriority++)
    ->addBlock('    <script type="text/javascript" src="'.$this->sitePrefixPath().'/js/bootstrap.min.js"></script>' . "\n", "bootstrap.min.js", $hbPriority++)
    ->addBlock('    <link href="'.$this->sitePrefixPath().'/images/pizza-icon.png" rel="shortcut icon" type="image/x-icon" />'."\n", "favicon.ico", $hbPriority++)
    ->addBlock('    <link href="'.$this->sitePrefixPath().'/css/style.css" media="all" rel="stylesheet" type="text/css" />' . "\n", "style.css", $hbPriority++)
    ->addBlock('    <script type="text/javascript" src="'.$this->sitePrefixPath().'/js/jquery-2.1.1.min.js"></script>' . "\n", "jquery.js", $hbPriority++)
    ;
?>
<!DOCTYPE HTML>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title><?php
        $titleParts = array();
        if ($this->headTitle() != "") {
            $titleParts[] = $this->headTitle();
        }
        $titleParts[] = "Пицца E96";
        echo $this->escape(implode(" — ", $titleParts));
        ?></title>
<?php echo $this->headBlock()->getHtml(); ?>
</head>
<body>

<?php if (!empty($user)) { ?>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->escape($this->sitePrefixPath() . "/"); ?>">Пицца E96</a>
    </div>
    <div class="navbar-collapse collapse">
        <form class="navbar-form navbar-right" role="form" action="<?php echo $this->escape($this->url("logout")); ?>" method="POST">
            <button type="submit" class="btn btn-primary">Выйти</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
           <li><a href="#"><?php echo $this->escape($user->real_name) ?> (<?php echo $this->escape($user->email) ?>)</a></li>
         </ul>

    </div>
  </div>
</div>
<?php } ?>
<div class="container">
<?php echo $content; ?>
</div>
</body>
</html>
