<?php
/**
 * Pizza E96
 *
 * @author: Paul Melekhov
 */

/** @var \App\TemplateEngine $this */
/** @var $request \App\Http\Request */
/** @var $exception \App\Http\Exception */

$title = "404 Страница не найдена";
$this->headTitle($title);
$this->headBlock()
    ->addBlock('    <link href="'.$this->sitePrefixPath().'/css/http_error.css" media="all" rel="stylesheet" type="text/css" />'."\n", "http_error.css")

?>
<h1><?php echo $this->escape($title); ?></h1>

<p>По указанному адресу <span class="request-uri"><?php echo $this->escape($request->getUrl()->getRelativeUrl()); ?></span> на
    нашем сервере страница не найдена.</p>

<?php if ($exception->getMessage() != ""): ?>
<blockquote><?php
    if ($exception->getCode() != 0) {
        echo "[" . $exception->getCode() . "] ";
    }
    echo $this->escape($exception->getMessage());
    ?></blockquote>
<?php endif; ?>
