<?php
/**
 * Шаблон блока скидки, когда формирование заказа идёт в данный момент
 */

/** @var \App\Models\OrdersRow $order */

?>
<div class="discountBanner">
    <p>Налетай, подешевело!</p>
    <p class="-title">СКИДКА: <?php
        $discounts = array();
        if ($order->discount_percent != 0) {
            $discounts[] = $order->discount_percent . "%";
        }
        if ($order->discount_absolute != 0) {
            $discounts[] = $order->discount_absolute . " руб.";
        }
        echo $this->escape(implode(" + ", $discounts));
    ?></p>
</div>
