<?php
/**
 * Created by PhpStorm.
 * User: paul
 * Date: 27.10.14
 * Time: 16:40
 */

/** @var \App\Models\OrdersRow $order */
/** @var \App\Models\RequestsRowset $myRequests */
/** @var array $orderPizzas */
/** @var float $priceMultiplier */
/** @var bool $hasDiscount */

?>
<h2>Мои заявки</h2>
<?php if (count($myRequests) > 0) {
    $readyPizzas = array();
    foreach ($orderPizzas as $orderPizza) {
        if ($orderPizza["ready"]) {
            $readyPizzas[] = $orderPizza["pizza_id"];
        }
    }
    $myTotalPrice = 0;
    $myTotalReadyPrice = 0;
    ?>

    <?php foreach ($myRequests as $request) {
        /** @var \App\Models\RequestsRow $request */

        $orderPizza = $orderPizzas[$request->pizza_id];
        $pizza = $request->getPizza();
        ?>
        <div class="panel panel-<?php echo in_array($request->pizza_id, $readyPizzas) ? "success" : "danger" ?>">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a href="<?php echo $this->escape($this->url("addPizza", array("orderId" => $order->id, "pizzaId" => $request->pizza_id))); ?>">
                        Пицца «<?php echo $this->escape($pizza->title) ?>»
                    </a>
                </h3>
            </div>
            <div class="panel-body myRequest">
                <img src="<?php echo $this->escape($pizza->image_url_small); ?>" alt="Фото" class="" />
                <p class="readyOrNot"><?php echo in_array($request->pizza_id, $readyPizzas) ? "Готова к заказу" : "Не готова, не хватает " . (8 - $orderPizza["total_pieces"] % 8) . " " . $this->plural((8 - $orderPizza["total_pieces"] % 8), "куска", "куска", "кусков") ?></p>
                <form style="float: right" id="logout_form_<?php echo $request->id ?>" action="<?php echo $this->escape($this->url("deletePizza", array("orderId" => $order->id, "requestId" => $request->id))); ?>" method="POST">
                    <button type="submit" class="btn">Удалить</button>
                </form>
                <p>Вы заказали: <?php echo $this->escape($request->pieces); ?> <?php echo $this->plural($request->pieces, "кусок", "куска", "кусков"); ?><br />
                Цена: <?php
                $myPrice = $pizza->price / 8 * $request->pieces;
                $myTotalPrice += $myPrice;
                $isReady = in_array($request->pizza_id, $readyPizzas);
                if ($isReady) {
                    $myTotalReadyPrice += $myPrice;
                }

                $priceFormulaPiece = round($pizza->price / 8, 2);
                if ($hasDiscount && $priceMultiplier != 1) {
                    $priceFormulaPiece = "(" . $priceFormulaPiece . " &minus; " . round((1 - $priceMultiplier) * $pizza->price / 8, 2) . ")";
                }
                $priceFormula = $request->pieces . " × " . $priceFormulaPiece . " = " . round($this->escape($myPrice * $priceMultiplier), 2);

                ?>
                <?php echo $priceFormula; ?> руб.
                <?php if ($hasDiscount && ! $isReady) { ?>
                    <em>(пока пицца не сформирована нельзя посчитать цену со скидкой)</em>
                <?php } ?>
                </p>
            </div>
        </div>
    <?php } ?>

    <p><a href="<?php echo $this->escape($this->url("selectPizza", [ "orderId" => $order->id ])); ?>">Добавить ещё заявку</a></p>

    <p class="myTotalPrice">Вам нужно сдать: <span class="price"><?php echo $this->escape(round(max(0, $myTotalReadyPrice * $priceMultiplier), 0)); ?> руб.</span>
        <?php if ($hasDiscount) { ?> (с учётом скидки)<?php } ?>
    </p>
<?php } else { ?>
    <p>У вас пока нет ни одной заявки на пиццу. <a href="<?php echo $this->escape($this->url("selectPizza", [ "orderId" => $order->id ])); ?>">Создать одну</a></p>
<?php } ?>
