<?php
/**
 * Pizza E96
 *
 * @author: Paul Melekhov
 */

/** @var \App\TemplateEngine $this */

$title = "Вход на сайт";
$this->headTitle($title);

/** @var $form \App\Forms\LoginForm */

$errors = array();

/*
 * Ошибки элементов формы
 */
$elementsErrors = $form->getElementsValidateErrors();
$elementsMessages = array(
    \App\Forms\Element::ERROR_REQUIRED => "Вы не указали %field%",
);
$fieldTitles = array(
    "email" => "E-mail",
    "password" => "пароль",
);
foreach ($elementsErrors as $name => &$elementErrors) {
    foreach ($elementErrors as $elementError) {
        $message = isset($elementsMessages[$elementError["code"]]) ? $elementsMessages[$elementError["code"]] : "%field% — ошибка {$elementError["code"]}";
        $errors[] = str_replace("%field%", isset($fieldTitles[$name]) ? $fieldTitles[$name] : $name, $message);
    }
}
unset($elementsErrors, $elementsMessages, $fieldTitles);

/*
 * Ошибки формы в целом
 */
$formErrors = $form->getFormValidateErrors();
$formMessages = array(
    \App\Forms\LoginForm::USER_NOT_FOUND => "Пользователь с таким e-mail не найден",
    \App\Forms\LoginForm::INVALID_IDENTITY => "Неправильный e-mail",
    \App\Forms\LoginForm::INVALID_PASSWORD => "Пароль введен неверно",
);
foreach ($formErrors as $message) {
    $errors[] = $formMessages[$message];
}

?>
<form class="form-signin" role="form" method="POST">
	<div class="logo"></div>
	<input type="email" class="form-control" name="email" placeholder="Email" value='<?php echo $this->escape($form->getValue("email"))?>' required autofocus>
	<input type="password" class="form-control" name="password" placeholder="Пароль" value='<?php echo $this->escape($form->getValue("password"))?>' required>
	<button class="btn btn-lg btn-primary btn-block" type="submit">войти</button>
	<div class="form-group">
		<p class="help-block text-center">Первый раз здесь? <a href="<?php echo $this->escape($this->url("register")); ?>">Регистрация</a></p>
	</div>
	<?php if (count($errors) > 0): ?>
		<div class="alert alert-danger" role="alert">
		<?php foreach ($errors as $error) {?>
			<p><?php echo $this->escape($error); ?></p>
		<?php } ?>
		</div>
	<?php endif ?>
</form>
