<?php
/**
 * Pizza E96
 *
 * @author: Paul Melekhov
 */

/** @var \App\TemplateEngine $this */

$title = "Вход на сайт";
$this->headTitle($title);

/** @var $form \App\Forms\LoginForm */

$errors = array();

/*
 * Ошибки элементов формы
 */
$elementsErrors = $form->getElementsValidateErrors();
$elementsMessages = array(
    \App\Forms\Element::ERROR_REQUIRED => "Вы не указали %field%",
);
$fieldTitles = array(
    "identity" => "номер мобильного телефона или E-mail",
    "password" => "пароль",
);
foreach ($elementsErrors as $name => &$messages) {
    foreach ($messages as $message) {
        if (isset($elementsMessages[$message])) {
            $errors[] = str_replace("%field%", $fieldTitles[$name], $elementsMessages[$message]);
        }
    }
}
unset($elementsErrors, $elementsMessages, $fieldTitles);

/*
 * Ошибки формы в целом
 */
$formErrors = $form->getFormValidateErrors();
$formMessages = array(
    \App\Forms\LoginForm::USER_NOT_FOUND => "Пользователь с таким e-mail не найден",
    \App\Forms\LoginForm::INVALID_IDENTITY => "Неправильный e-mail",
    \App\Forms\LoginForm::INVALID_PASSWORD => "Пароль введен неверно",
);
foreach ($formErrors as $message) {
    $errors[] = $formMessages[$message];
}

?>

<h1>Пицца E96</h1>

<h2><?php echo $this->escape($title); ?></h2>

<form class='page-message__form' action="" method="POST">
	<div class='page-message__text'>
		Адрес электронной почты:
	</div>
	<div class='page-message__form-input'>
		<input placeholder='электронная почта' type='text' name='email' value='<?php echo $this->escape($form->getValue("email"))?>' />
	</div>
	<div class='page-message__text'>
		Пароль:
	</div>
	<div class='page-message__form-input'>
		<input placeholder='пароль' type='password' name='password' value='<?php echo $this->escape($form->getValue("password"))?>' />
	</div>
	<div class='page-message__form-submit'>
		<input type='submit' value='Войти' />
	</div>
</form>

<p>Первый раз здесь? Тогда вам <a href="<?php echo $this->escape($this->url("register")); ?>">сюда</a> (регистрация).</p>

<?php if (count($errors) > 0): ?>
    <script type="text/javascript">
        $(document).ready(function() {
            setTimeout(function() {
                alert('<?php echo addslashes($errors[0]) ?>');
            }, 500);
        });
    </script>
<?php endif ?>
