<?php
/**
 * Pizza E96
 *
 * @author: Paul Melekhov
 */

/** @var \App\TemplateEngine $this */
/** @var \App\Models\RequestsRowset $myRequests */
/** @var array $orderPizzas */
/** @var \App\Models\OrdersRow $order */
/** @var int $orderPrice */

$title = "Заказ №" . $order->id . " &mdash; Пицца E96";

$priceMultiplier = $orderPrice != 0 ? 1 - $order->discount_percent / 100 - $order->discount_absolute / $orderPrice : 0;
$hasDiscount = $order->discount_absolute != 0 || $order->discount_percent != 0;
$isActive = $order->status == \App\Models\OrdersRow::STATUS_ACTIVE;

?>
<h2>Заказ № <?php echo $this->escape($order->id) ?></h2>
<div class="alert alert-warning" role="alert">
    Доставка на <?php echo $this->escape(date("j M Y, H:i", strtotime($order->delivery))); ?>.
</div>

<p><strong>Статус: <?php echo $this->escape($order->getCurrentStatusText()); ?></strong></p>

<?php if ($hasDiscount) { ?>
<?php if ($isActive) {
        echo $this->partial("partials/discount_active.phtml", [ "order" => $order ]);
    } else {
        echo $this->partial("partials/discount_passive.phtml", [ "order" => $order ]);
    } ?>
<?php } ?>

<?php if ($isActive) {
    echo $this->partial("partials/my_requests.phtml", [
        "order" => $order,
        "myRequests" => $myRequests,
        "orderPizzas" => $orderPizzas,
        "priceMultiplier" => $priceMultiplier,
        "hasDiscount" => $hasDiscount,
    ]);
} ?>

<h2>Общий заказ</h2>
<?php if (!empty($orderPizzas)) {
    $userPrices = array();

    ?>

    <?php foreach ($orderPizzas as $orderPizza) { ?>
        <?php if (! $isActive && ! $orderPizza["ready"]) {
            continue;
        } ?>
        <div class="panel panel-<?php echo $orderPizza["ready"] ? "success" : "danger" ?>">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a href="<?php echo $this->escape($this->url("addPizza", array("orderId" => $order->id, "pizzaId" => $orderPizza["pizza_id"]))); ?>">Пицца «<?php echo $this->escape($orderPizza["title"]) ?>»</a>
                </h3>
            </div>
            <div class="panel-body commonOrderItem">
                <div class="pizzaInfo">
                    <a href="<?php echo $this->escape($this->url("addPizza", array("orderId" => $order->id, "pizzaId" => $orderPizza["pizza_id"]))); ?>"><img src="<?php echo $this->escape($orderPizza["image_url_medium"]); ?>" alt="Фото" /></a>
                    <p class="price">Цена: <?php echo $this->escape($orderPizza["price"]); ?> руб.
                    </p>
                </div>

                <?php if ($isActive) { ?>
                    <p class="readyOrNot"><?php echo $orderPizza["ready"] ? "Готова к заказу" : "Не готова, не хватает " . (8 - $orderPizza["total_pieces"] % 8) . " " . $this->plural((8 - $orderPizza["total_pieces"] % 8), "куска", "кусков", "кусков"); ?></p>
                <?php } ?>
                <table class="table commonOrder">
                    <?php foreach ($orderPizza["requests"] as $request) {
                        /** @var \App\Models\RequestsRow $request */
                        if ($orderPizza["ready"]) {
                            if (empty($userPrices[$request->getUser()->id])) {
                                $userPrices[$request->getUser()->id] = array(
                                    "user" => $request->getUser(),
                                    "totalPrice" => 0,
                                );
                            }
                            $userPrices[$request->getUser()->id]["totalPrice"] += ($orderPizza["price"] / 8 * $request->pieces);
                        }
                        ?>

                        <tr>
                            <td class="realName"><?php echo $this->escape($request->getUser()->real_name) ?></td>
                            <td class="pieces"><?php echo $this->escape($request->pieces) ?> <?php echo $this->plural($request->pieces, "кусок", "куска", "кусков"); ?></td>
                        </tr>
                    <?php } /* foreach ($orderPizza["requests"] ...) */ ?>
                </table>

                <?php if ($isActive) { ?>
                <form action="<?php echo $this->escape($this->url("addPizza", array("orderId" => $order->id, "pizzaId" => $orderPizza["pizza_id"]))); ?>" method="post">
                    <label for="pieces">Добавить себе кусочек этой пиццы:</label>
                    <input id="pieces" type="text" name="pieces" value="1" maxlength="2" size="2" />
                    <input type="submit" name="" value="Тоже хочу!" />
                </form>
                <?php } ?>

            </div>
        </div>
    <?php } /* foreach ($orderPizzas ...) */ ?>

    <p class="totalOrderPrice">Общая стоимость заказа: <span class="price"><?php echo $this->escape(round($orderPrice * $priceMultiplier)); ?> руб.</span>
        <?php if (round($orderPrice * $priceMultiplier) != $orderPrice) { ?>(без скидки было бы: <?php echo $this->escape($orderPrice); ?> руб.)<?php } ?>
    </p>

    <?php if (count($userPrices) != 0) { ?>
        <h3>Кто, что и сколько заказал</h3>

        <table class="table order-per-user-details">
            <?php
            $borderTopNone = ' style="border-top: none"';
            foreach ($userPrices as $userPrice) {
            ?>

                <tr>
                    <td<?php echo $borderTopNone ?> class="username"><?php echo $this->escape($userPrice["user"]->real_name); ?></td>
                    <td<?php echo $borderTopNone ?>><?php
                        foreach ($orderPizzas as $orderPizza) {
                            if (! $orderPizza["ready"]) {
                                continue;
                            }
                            foreach ($orderPizza["requests"] as $request) {
                                if ($request["user_id"] == $userPrice["user"]->id) {
                                    echo $request["pieces"], " × ", $this->escape($orderPizza["title"]), "<br />";
                                }
                            }
                        }
                     ?></td>
                    <td<?php echo $borderTopNone ?> class="price"><?php echo $this->escape(round($userPrice["totalPrice"] * $priceMultiplier, 0)); ?> руб.</td>
                </tr>
            <?php
                $borderTopNone = "";
            } ?>
        </table>
    <?php } ?>
<?php if (! $isActive) { ?>
    <p class="printButton"><button onclick="print()">Печать...</button></p>
<?php } ?>
<?php } else { ?>
    <p>Заказ пустой.</p>
<?php } ?>
