<?php
/**
 * Pizza E96
 *
 * @author: Paul Melekhov
 */

/** @var \App\TemplateEngine $this */
/** @var \App\Models\RequestsRowset $myRequests */
/** @var array $orderPizzas */
/** @var \App\Models\OrdersRow $order */
/** @var int $orderPrice */
/** @var bool $canEdit */

$title = "Заказ №" . $order->id . " &mdash; Пицца E96";

$priceMultiplier = $orderPrice != 0 ? 1 - $order->discount_percent / 100 - $order->discount_absolute / $orderPrice : 0;
$hasDiscount = $order->discount_absolute != 0 || $order->discount_percent != 0;
$isActive = $order->status == \App\Models\OrdersRow::STATUS_ACTIVE;

?>
<?php if ($canEdit) { ?>
<p style="float: right"><a href="<?php echo $this->escape($this->url("editOrder", [ "orderId" => $order->id ])); ?>">Редактировать заказ</a></p>
<?php } ?>

<h1>Заказ № <?php echo $this->escape($order->id) ?>
<?php
$btnClassByStatus = function($status) {
    $classes = [
        \App\Models\OrdersRow::STATUS_ACTIVE => "btn-primary",
        \App\Models\OrdersRow::STATUS_FIXED  => "btn-warning",
        \App\Models\OrdersRow::STATUS_ORDERED => "btn-info",
        \App\Models\OrdersRow::STATUS_DELIVERED => "btn-success",
        \App\Models\OrdersRow::STATUS_CANCELLED => "btn-danger",
    ];
    return !empty($classes[$status]) ? $classes[$status] : "btn-default";
};
?>
<?php if ($canEdit) { ?>
<span class="btn <?php echo $btnClassByStatus($order->status); ?>" style="margin-left: 2em; margin-top: -5px;" data-toggle="modal" data-target="#changeStatusModal"><?php echo $this->escape($order->getCurrentStatusText()); ?></span>
<?php } else { ?>
<span class="btn <?php echo $btnClassByStatus($order->status); ?>" style="margin-left: 2em; margin-top: -5px;" disabled><?php echo $this->escape($order->getCurrentStatusText()); ?></span>
<?php } ?>
</h1>

<div class="bg-info" style="padding: 1em 1em;">
    Доставка на <?php echo $this->escape(date("j M Y, H:i", strtotime($order->delivery))); ?>.
</div>

<?php if ($order->note != "") { ?>
<blockquote><?php echo $this->escape($order->note); ?></blockquote>
<?php } ?>

<?php if ($canEdit) { ?>
<div class="modal fade" id="changeStatusModal" tabindex="-1" role="dialog" aria-labelledby="changeStatusModalLabel" aria-hidden="true">
    <form action="<?php echo $this->escape($this->url("statusOrder", [ "orderId" => $order->id ] )); ?>" method="post" class="form-horizontal changeStatus">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="changeStatusModalLabel">Изменить статус</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="radios">Статус:</label>
                        <div class="col-md-4">
                            <?php
                            $statuses = [
                                \App\Models\OrdersRow::STATUS_ACTIVE,
                                \App\Models\OrdersRow::STATUS_FIXED,
                                \App\Models\OrdersRow::STATUS_ORDERED,
                                \App\Models\OrdersRow::STATUS_DELIVERED,
                                \App\Models\OrdersRow::STATUS_CANCELLED,
                            ];
                            $n = 0;
                            foreach ($statuses as $status) { ?>
                                <div class="radio">
                                    <label for="radios-<?php echo $n; ?>">
                                        <input type="radio" name="status" id="radios-<?php echo $n; ?>" value="<?php echo $this->escape($status); ?>"<?php if ($order->status == $status) { echo ' checked="checked"'; } ?>>
                                        <?php echo $this->escape(\App\Models\OrdersRow::getStatusText($status)); ?>
                                    </label>
                                </div>
                            <?php $n++; } ?>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Сохранить статус</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </form>
</div>
<?php } ?>

<?php if ($hasDiscount) { ?>
<?php if ($isActive) {
        echo $this->partial("partials/discount_active.phtml", [ "order" => $order ]);
    } else {
        echo $this->partial("partials/discount_passive.phtml", [ "order" => $order ]);
    } ?>
<?php } ?>

<?php if ($isActive) {
    echo $this->partial("partials/my_requests.phtml", [
        "order" => $order,
        "myRequests" => $myRequests,
        "orderPizzas" => $orderPizzas,
        "priceMultiplier" => $priceMultiplier,
        "hasDiscount" => $hasDiscount,
    ]);
} ?>

<h2>Общий заказ</h2>
<?php if (!empty($orderPizzas)) {
    $userPrices = array();

    ?>

    <?php foreach ($orderPizzas as $orderPizza) { ?>
        <?php if (! $isActive && ! $orderPizza["ready"]) {
            continue;
        } ?>
        <div class="panel panel-<?php echo $orderPizza["ready"] ? "success" : "danger" ?>">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a href="<?php echo $this->escape($this->url("addPizza", array("orderId" => $order->id, "pizzaId" => $orderPizza["pizza_id"]))); ?>">Пицца «<?php echo $this->escape($orderPizza["title"]) ?>»</a>
                </h3>
            </div>
            <div class="panel-body commonOrderItem">
                <div class="pizzaInfo">
                    <a href="<?php echo $this->escape($this->url("addPizza", array("orderId" => $order->id, "pizzaId" => $orderPizza["pizza_id"]))); ?>"><img src="<?php echo $this->escape($orderPizza["image_url_medium"]); ?>" alt="Фото" /></a>
                    <p class="price">Цена: <?php echo $this->escape($orderPizza["price"]); ?> руб.<br />(по <?php echo $this->escape(round($orderPizza["price"] / 8)); ?> руб. за кусок)</p>
                </div>

                <?php if ($isActive) { ?>
                    <p class="readyOrNot"><?php echo $orderPizza["ready"] ? "Готова к заказу" : "Не готова, не хватает " . (8 - $orderPizza["total_pieces"] % 8) . " " . $this->plural((8 - $orderPizza["total_pieces"] % 8), "куска", "кусков", "кусков"); ?></p>
                <?php } ?>
                <table class="table commonOrder">
                    <?php foreach ($orderPizza["requests"] as $request) {
                        /** @var \App\Models\RequestsRow $request */
                        if ($orderPizza["ready"]) {
                            if (empty($userPrices[$request->getUser()->id])) {
                                $userPrices[$request->getUser()->id] = array(
                                    "user" => $request->getUser(),
                                    "totalPrice" => 0,
                                );
                            }
                            $userPrices[$request->getUser()->id]["totalPrice"] += ($orderPizza["price"] / 8 * $request->pieces);
                        }
                        ?>

                        <tr>
                            <td class="realName"><?php echo $this->escape($request->getUser()->real_name) ?></td>
                            <td class="pieces"><?php echo $this->escape($request->pieces) ?> <?php echo $this->plural($request->pieces, "кусок", "куска", "кусков"); ?></td>
                        </tr>
                    <?php } /* foreach ($orderPizza["requests"] ...) */ ?>
                </table>

                <?php if ($isActive) { ?>
                <form action="<?php echo $this->escape($this->url("addPizza", array("orderId" => $order->id, "pizzaId" => $orderPizza["pizza_id"]))); ?>" method="post">
                    <label for="pieces">Добавить себе кусочек этой пиццы:</label>
                    <input id="pieces" type="text" name="pieces" value="1" maxlength="2" size="2" />
                    <input type="submit" name="" value="Тоже хочу!" />
                </form>
                <?php } ?>

            </div>
        </div>
    <?php } /* foreach ($orderPizzas ...) */ ?>

    <p class="totalOrderPrice">Общая стоимость заказа: <span class="price"><?php echo $this->escape(round($orderPrice * $priceMultiplier)); ?> руб.</span>
        <?php if (round($orderPrice * $priceMultiplier) != $orderPrice) { ?>(без скидки было бы: <?php echo $this->escape($orderPrice); ?> руб.)<?php } ?>
    </p>

    <?php if (count($userPrices) != 0) { ?>
        <h3>Кто, что и сколько заказал</h3>

        <table class="table order-per-user-details">
            <?php
            $borderTopNone = ' style="border-top: none"';
            foreach ($userPrices as $userPrice) {
            ?>

                <tr>
                    <td<?php echo $borderTopNone ?> class="username"><?php echo $this->escape($userPrice["user"]->real_name); ?></td>
                    <td<?php echo $borderTopNone ?>><?php
                        foreach ($orderPizzas as $orderPizza) {
                            if (! $orderPizza["ready"]) {
                                continue;
                            }
                            foreach ($orderPizza["requests"] as $request) {
                                if ($request["user_id"] == $userPrice["user"]->id) {
                                    echo $request["pieces"], " × ", $this->escape($orderPizza["title"]), "<br />";
                                }
                            }
                        }
                     ?></td>
                    <td<?php echo $borderTopNone ?> class="price"><?php echo $this->escape(round($userPrice["totalPrice"] * $priceMultiplier, 0)); ?> руб.</td>
                </tr>
            <?php
                $borderTopNone = "";
            } ?>
        </table>
    <?php } ?>
<?php } else { ?>
    <p>Заказ пустой.</p>
<?php } ?>

<div>Организатор этого заказа: <?php echo $this->escape($order->getCreator()->real_name); ?></div>
<?php if (!empty($orderPizzas) && ! $isActive) { ?>
    <p class="printButton"><button onclick="print()">Печать...</button></p>
<?php } ?>

