<?php
/**
 * Pizza E96
 *
 * @author: Paul Melekhov
 */

/** @var \App\TemplateEngine $this */

$title = "Регистрация на сайте";
$this->headTitle($title);

/** @var $form \App\Forms\RegisterForm */

$errors = array();


$getErrorMessage = function($error, $fieldName)
{
    if ($fieldName == "password" && $error["name"] == "length") {
        $message = isset($error["data"]["minLength"]) ? "Пароль должен быть не менее {$error["data"]["minLength"]} символов" : "Слишком короткий пароль";
    } elseif ($fieldName == "realName" && $error["name"] == "length") {
        $message = isset($error["data"]["minLength"]) ? "%field% должно быть не менее {$error["data"]["minLength"]} символов" : "Слишком короткое %field%";
    } else {
        $elementsMessages = array(
            \App\Forms\Element::ERROR_REQUIRED => "%field% — обязательное поле",
            \App\Validators\Email::INVALID_EMAIL => "%field% указан неправильно",
            \App\Validators\RegexpMatch::REGEXP_DOES_NOT_MATCH => "%field% не соответствует регулярному выражению",
        );
        $message = isset($elementsMessages[$error["code"]])
            ? $elementsMessages[$error["code"]]
            : "%field% — ошибка {$error["code"]}";
    }
    // Заменяем %field% на имя поля
    $fieldTitles = array(
        "email" => "E-mail",
        "password" => "Пароль",
        "realName" => "Настоящее имя",
    );
    $message = str_replace("%field%", isset($fieldTitles[$fieldName]) ? $fieldTitles[$fieldName] : $fieldName, $message);
    return $message;
};

/*
 * Ошибки элементов формы
 */
foreach ($form->getElementsValidateErrors() as $fieldName => $elementErrors) {
    foreach ($elementErrors as $elementError) {
        $errors[] = $getErrorMessage($elementError, $fieldName);
    }
}

/*
 * Ошибки формы в целом
 */
$formErrors = $form->getFormValidateErrors();
$formMessages = array(
    \App\Forms\RegisterForm::ERROR_NO_EMAIL => "Вы должны ввести e-mail",
    "emailExists" => "Указанный электронный адрес уже зарегистрирован",
);
foreach ($formErrors as $message) {
    $errors[] = isset($formMessages[$message]) ? $formMessages[$message] : $message;
}

?>
<form class="form-signin form-signin-register" role="form" method="POST">

<div class="logo"></div>

<input type="email" class="form-control" name="email" placeholder="Email" value='<?php echo $this->escape($form->getValue("email"))?>' required autofocus>
<input type="password" class="form-control" name="password" placeholder="Пароль" value='<?php echo $this->escape($form->getValue("password"))?>' required>
<input type="text" class="form-control" name="realName" placeholder="Настоящее имя" value='<?php echo $this->escape($form->getValue("realName"))?>' required>

<button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
<div class="form-group">
	<p class="help-block text-center">Передумал, хочу <a href="<?php echo $this->escape($this->url("login")) ?>">войти</a>.</p>
</div>
<?php if (count($errors) > 0): ?>
	<div class="alert alert-danger" role="alert">
	<?php foreach ($errors as $error) {?>
		<p><?php echo $this->escape($error); ?></p>
	<?php } ?>
	</div>
<?php endif ?>
</form>