<?php
/**
 * Pizza E96
 *
 * @author: Paul Melekhov
 */

/** @var $this App\TemplateEngine */
/** @var \App\Models\PizzasRowset $pizzas */
/** @var int $orderId */

$title = "Выберите пиццу";
$this->headTitle($title);

?>
<h1><?php echo $this->escape($title); ?></h1>

<table>
<?php foreach ($pizzas as $pizza) {
    /** @var \App\Models\PizzasRow $pizza */

    ?>

    <tr>
        <td class="title-and-image"><a href="<?php echo $this->escape($this->url("addPizza", array("orderId" => $orderId, "pizzaId" => $pizza->id))); ?>"><?php echo $this->escape($pizza->title); ?><br />
            <img src="<?php echo $this->escape($pizza->image_url_medium) ?>" alt="Фото" /></a></td>
        <td class="description"><?php echo nl2br($this->escape($pizza->description)); ?></td>
        <td class="price"><?php echo $this->escape($pizza->price); ?> руб.</td>
    </tr>
<?php } ?>

</table>